# Generated by Django 2.2.2 on 2020-12-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='achievement_summary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_id', models.CharField(max_length=255)),
                ('s_name', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('s_type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('journal', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('achievement', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='paper_summary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_id', models.CharField(max_length=255)),
                ('s_name', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('s_type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('journal', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('publish', models.CharField(max_length=255)),
                ('included', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='patent_summary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_id', models.CharField(max_length=255)),
                ('s_name', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('s_type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('p_type', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='project_summary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_id', models.CharField(max_length=255)),
                ('s_name', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('s_type', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=255)),
                ('p_id', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('fund', models.CharField(max_length=255)),
                ('principal', models.CharField(max_length=255)),
            ],
        ),
    ]
