# Generated by Django 2.2.2 on 2021-10-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patoffs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patent_summary',
            old_name='number',
            new_name='pat_id',
        ),
        migrations.RemoveField(
            model_name='achievement_summary',
            name='journal',
        ),
    ]
