# Generated by Django 2.2.2 on 2020-11-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='te_college_16c',
            fields=[
                ('college', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_college_16q',
            fields=[
                ('college', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_college_17c',
            fields=[
                ('college', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_college_17q',
            fields=[
                ('college', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_college_18c',
            fields=[
                ('college', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_college_18q',
            fields=[
                ('college', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_college_19c',
            fields=[
                ('college', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_college_19q',
            fields=[
                ('college', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_college_20q',
            fields=[
                ('college', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_course_16c',
            fields=[
                ('c_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=30)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_course_16q',
            fields=[
                ('c_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=30)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_course_17c',
            fields=[
                ('c_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=30)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_course_17q',
            fields=[
                ('c_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=30)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_course_18c',
            fields=[
                ('c_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=30)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_course_18q',
            fields=[
                ('c_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=30)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_course_19c',
            fields=[
                ('c_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=30)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_course_19q',
            fields=[
                ('c_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=30)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_course_20q',
            fields=[
                ('c_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=30)),
                ('ave_score', models.FloatField()),
            ],
        ),
    ]
