# Generated by Django 2.2.2 on 2021-10-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tevalution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='te_college',
            fields=[
                ('semester', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_college_20c',
            fields=[
                ('college', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_course',
            fields=[
                ('semester', models.CharField(max_length=20)),
                ('t_name', models.CharField(max_length=30)),
                ('c_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=30)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_course_20c',
            fields=[
                ('c_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=30)),
                ('ave_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='te_tiaotingke',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=30)),
                ('cl_name', models.CharField(max_length=255)),
                ('c_name', models.CharField(max_length=255)),
                ('c_id', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('case', models.TextField()),
                ('content', models.TextField()),
                ('type', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tea_evalution_summary',
            fields=[
                ('semester', models.CharField(max_length=20)),
                ('TE_id', models.IntegerField(primary_key=True, serialize=False)),
                ('college', models.CharField(max_length=30)),
                ('c_id', models.CharField(max_length=255)),
                ('c_name', models.CharField(max_length=255)),
                ('cl_name', models.CharField(max_length=255)),
                ('t_id', models.CharField(max_length=30)),
                ('t_name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('Ave_score', models.FloatField()),
                ('s_id', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('advise', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tea_evalution_summary_20c',
            fields=[
                ('TE_id', models.IntegerField(primary_key=True, serialize=False)),
                ('college', models.CharField(max_length=30)),
                ('c_id', models.CharField(max_length=255)),
                ('c_name', models.CharField(max_length=255)),
                ('cl_name', models.CharField(max_length=255)),
                ('t_id', models.CharField(max_length=30)),
                ('t_name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('Ave_score', models.FloatField()),
                ('s_id', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('advise', models.TextField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='te_course_16c',
            name='c_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='te_course_16q',
            name='c_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='te_course_17c',
            name='c_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='te_course_17q',
            name='c_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='te_course_18c',
            name='c_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='te_course_18q',
            name='c_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='te_course_19c',
            name='c_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='te_course_19q',
            name='c_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='te_course_20q',
            name='c_name',
            field=models.CharField(max_length=255),
        ),
    ]
