# Generated by Django 2.2.2 on 2020-07-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cf_summary19',
            fields=[
                ('id', models.IntegerField(max_length=7, primary_key=True, serialize=False)),
                ('s_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('mentor', models.CharField(max_length=255)),
                ('cfname', models.CharField(max_length=255)),
                ('cfcategory', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('form', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('subsidy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='college_declare',
            fields=[
                ('college', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('declare', models.IntegerField()),
                ('successful', models.IntegerField()),
            ],
        ),
    ]
