# Generated by Django 2.2.2 on 2020-09-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cf_category_declare_19',
            fields=[
                ('category', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('declare', models.IntegerField()),
                ('successful', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cf_cfname_declare_19',
            fields=[
                ('cfname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('declare', models.IntegerField()),
                ('successful', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cf_college_declare_19',
            fields=[
                ('college', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('declare', models.IntegerField()),
                ('successful', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cf_condition_declare_19',
            fields=[
                ('condition', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('declare', models.IntegerField()),
                ('successful', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cf_country_declare_19',
            fields=[
                ('country', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('declare', models.IntegerField()),
                ('successful', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cf_form_declare_19',
            fields=[
                ('form', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('declare', models.IntegerField()),
                ('successful', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cf_major_declare_19',
            fields=[
                ('major', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('declare', models.IntegerField()),
                ('successful', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cf_mentor_declare_19',
            fields=[
                ('mentor', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('declare', models.IntegerField()),
                ('successful', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='college_declare',
        ),
        migrations.AddField(
            model_name='cf_summary19',
            name='approved',
            field=models.CharField(default='未过', max_length=2),
        ),
    ]
