# Generated by Django 2.2.2 on 2020-09-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0002_auto_20200921_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cf_summary19',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
