# Generated by Django 2.2.2 on 2021-04-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qianxuesen_banji',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('banji', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('cl_id', models.CharField(max_length=255)),
                ('cl_name', models.CharField(max_length=255)),
                ('t_name', models.CharField(max_length=255)),
                ('t_college', models.CharField(max_length=255)),
                ('time1', models.CharField(max_length=255)),
                ('time2', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('week', models.CharField(max_length=255)),
                ('sord', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='qianxuesen_class',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('banji', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('cl_id', models.CharField(max_length=255)),
                ('cl_name', models.CharField(max_length=255)),
                ('t_name', models.CharField(max_length=255)),
                ('t_college', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('week', models.CharField(max_length=255)),
                ('sord', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='qianxuesen_summary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('cescore', models.IntegerField()),
                ('prrank', models.IntegerField()),
                ('score1', models.FloatField()),
                ('score2', models.FloatField()),
                ('score3', models.FloatField()),
                ('score4', models.FloatField()),
                ('rank', models.IntegerField()),
                ('major', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='qianxuesen_trainingplan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cl_kind', models.CharField(max_length=255)),
                ('cl_id', models.CharField(max_length=255)),
                ('cl_name', models.CharField(max_length=255)),
                ('cl_ename', models.CharField(max_length=255)),
                ('languange', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('credit', models.FloatField()),
            ],
        ),
    ]
